

2012-06-25 16:48:58
 WARNING: SCANNER RESOURCES: Unclaimed at start-up ['Scanner 1', 'Scanner 2', 'Scanner 3']


2012-06-25 16:48:58
 WARNING: SCANNER RESOURCES: Scanners that are on: None


2012-06-25 16:49:27
 CRITICAL: Uncaught exception:
Traceback (most recent call last):
  File "/home/martin/Documents/PhD/python/scannomatic/src/gui_grid.py", line 254, in _set_update_pinning_matrix
    self.make_repinning()
  File "/home/martin/Documents/PhD/python/scannomatic/src/gui_grid.py", line 305, in make_repinning
    grid_lock = True, verboise=False, visual=False)
  File "/home/martin/Documents/PhD/python/scannomatic/src/analysis_grid_array.py", line 259, in set_grid
    best_fit_columns[column], 'r-')
IndexError: list index out of range
